### ISSUE TITLE
电力巡检系统（毕设

### ISSUE THREAD

**Issue by tenderzada** [WinstonLy/Electricity-Inspection-Based-Ascend310#2]
最近在做电力巡检系统（毕设）,我用了yolov5来训练模型。但是一直不知道怎么解决视频流问题，你有什么经验分享的话我将万分感谢。

**Comment by WinstonLy** [comment]
视频流问题具体是指什么呢？

**Comment by tenderzada** [comment]
简单来说，
step1: 摄像头采集到的数据能实时传回来（类似大疆无人机）。
setp2: 用训练好的模型去分析视频中是否存在故障。
我本身是学软件开发的，所以setp1实现不了，你有什么好的替代方案吗。

**Comment by tenderzada** [comment]
简单来说，
step1: 摄像头采集到的数据能实时传回来（类似大疆无人机）。
setp2: 用训练好的模型去分析视频中是否存在故障。
我本身是学软件开发的，所以setp1实现不了，你有什么好的替代方案吗。

**Comment by WinstonLy** [comment]
我觉得最关键的是先搞懂摄像头地传输协议，即摄像头通过什么方式发送数据（网口？或者其他），物理层怎么连接，协议层怎么实现，最后到应用层实现。你根据协议再去想办法接收数据。摄像头采集，如果是大疆平台，自身会有一套SDK来获取数据，应该会提供相应的API接口，你需要在SDK基础上进行你的软件开发，将你的软件嵌入到大疆平台中；如果大疆无人机仅仅作为一个载体，有其他的摄像头，要根据摄像头传输协议利用opencv、ffmpeg等这些开源库来捕获视频流。
仅仅是我的一点意见，我不是很清楚你具体的流程是怎么样的。
